Repository vishnu2k60/MyIdentityCard, pull requests merged in 2022-10, with the labels that each got.

#1 Update index.html
  index.html
Labels: hacktoberfest-accepted

#2 Update index.html
  index.html
Labels: hacktoberfest-accepted

#3 Update index.html
  index.html
Labels: hacktoberfest-accepted

#4 Update index.html
  index.html
Labels: hacktoberfest-accepted

#6 Harsh2801 patch 1
  index.html
Labels: hacktoberfest-accepted

#11 Add Detail
  index.html
Labels: hacktoberfest-accepted

#12 Update index.html
  index.html
Labels: hacktoberfest-accepted

#13 Update index.html
  index.html
Labels: hacktoberfest-accepted

#14 Update index.html
  index.html
Labels: hacktoberfest-accepted

#16 Update index.html
  index.html
Labels: hacktoberfest-accepted

#17 Update index.html
  index.html
Labels: hacktoberfest-accepted

#18 Update index.html
  index.html
Labels: hacktoberfest-accepted

#19 Update index.html
  index.html
Labels: invalid

#20 Update index.html
  index.html
Labels: hacktoberfest-accepted

#21 Update index.html
  index.html
Labels: hacktoberfest-accepted

#22 Yo
  index.html
Labels: hacktoberfest-accepted

#23 Update index.html
  index.html
Labels: hacktoberfest-accepted

#24 Update index.html
  index.html
Labels: hacktoberfest-accepted

#27 Add files via upload
  subsequences.cpp
Labels: hacktoberfest-accepted

#28 Update index.html
  index.html
Labels: hacktoberfest-accepted

#29 Update index.html
  index.html
Labels: hacktoberfest-accepted

#30 Updated
  index.html
Labels: hacktoberfest-accepted

#31 Added Links to github & Linkedin
  index.html
Labels: hacktoberfest-accepted

#32 added my details
  index.html
Labels: hacktoberfest-accepted

#33 Update index.html
  index.html
Labels: hacktoberfest-accepted

#34 Update index.html
  index.html
Labels: hacktoberfest-accepted

#35 Update index.html
  index.html
Labels: invalid, hacktoberfest-accepted

#38 Updated the CONTRIBUTING.md
  CONTRIBUTING.md
Labels: invalid, hacktoberfest-accepted

#53 Added my Name Block in index.html file
  index.html
Labels: invalid, hacktoberfest-accepted
